### ISSUE TITLE
.find removes ID from element

### ISSUE THREAD

**Issue by xolir** [strudeljs/strudel#103]
**Describe the bug**
If element instance has ID and .find is being used on it ID is being removed. 

**Expected behavior**
ID stays on instance

**Desktop (please complete the following information):**
All Platforms

**Comment by xolir** [comment]
I think we may consider removing this weird `>` usage and add `:scope` polyfill instead

**Comment by mateuszluczak** [comment]
Let's rely on some stupid ass random data attribute instead of id. This is what these polyfills do.

**Comment by xolir** [comment]
At least they don't remove it 🤷‍♂

**Comment by mateuszluczak** [comment]
You can still use :scope if you want, as it's native API.
