### ISSUE TITLE
Inline SVG element causes errors in initialization module

### ISSUE THREAD

**Issue by xolir** [strudeljs/strudel#107]
**Describe the bug**
Whenever SVG element is placed on page automatic initialization fails as component detection treats it not as HTML element but collection.

`element = detail[0] instanceof HTMLElement ? detail[0] : detail[0].first();`

throws ` Uncaught TypeError: detail[0].first is not a function`

**To Reproduce**
1. Insert SVG element dynamically

**Expected behavior**
Error is not being thrown, SVG is being handled properly

**Comment by mateuszluczak** [comment]
@xolir any update on this? Should this be handled before 1.0.0 release?

**Comment by xolir** [comment]
@mateuszluczak what update would you expect on this?

**Comment by mateuszluczak** [comment]
Update in regards - is this something that you are planning to do or maybe in hands of @grazik or should I find someone for this.

I agree regarding including it 1.0.0.
