### ISSUE TITLE
Warn when component is tried to attached to a node already having a component

### ISSUE THREAD

**Issue by mateuszluczak** [strudeljs/strudel#58]
**Is your feature request related to a problem? Please describe.**
Currently when developer creates a component that conflicts with selector of already existing one component is silently not attached - it may be hard to understand why the component is not working.

**Describe the solution you'd like**
`console.warn` in development mode should be displayed.

**Comment by xolir** [comment]
Is this still valid issue? I can see console error being thrown on already initialised node.

**Comment by mateuszluczak** [comment]
Are you sure?
https://github.com/strudeljs/strudel/blob/dev/src/core/linker.js#L48 - here looks like there is no message
