### ISSUE TITLE
Development mode tip always present in devtools

### ISSUE THREAD

**Issue by mlmmn** [strudeljs/strudel#70]
**Describe the bug**
Despite setting the `production` mode in the webpack, the Strudel is still showing that the project was built in `development` mode.

**To Reproduce**
Build Strudel-dependent project in `production` mode.

**Expected behavior**
Production tip is not present on actual production build.

**Additional context**
`strudel.js` build checks one condition which is always true
```javascript
/**
* Whether to show production mode tip message on boot
*/
productionTip: "development" !== 'production'
```

**Comment by mateuszluczak** [comment]
Hi @mlmmn, thanks for raising this issue.

In additional context I can see that you are referring to `strudel.js` file - this file is intended to be in development mode. If you want to use compiled file in production mode you should use `strudel.min.js` instead. 

I would strongly recommend though using ES Module file `strudel.esm.js` to enable production mode on webpack level for using with other code-optimisation techniques like tree-shaking.

Please refer to the docs for details: https://strudeljs.org/guide/deployment.html

Cheers

**Comment by mlmmn** [comment]
I have followed the docs - despite setting `mode: production` in webpack is there anything that should be configured? Now no matter what, webpack always picks the `strudel.js` file.

**Comment by mateuszluczak** [comment]
Simplest possible option is to add alias in your `webpack.config.js` like following:

````
resolve: {
  alias: {
      'strudel$': 'strudel/dist/strudel.esm.js'
  }
}
```

this may also require changing your `babel-loader` config to include this module if you have `node_modules` excluded.
