### ISSUE TITLE
Export constant containing 'strudel-init' class name

### ISSUE THREAD

**Issue by pawel-staniszewski** [strudeljs/strudel#77]
**Is your feature request related to a problem? Please describe.**
When trying to find initialised components within a scope, I need to know the class name Strudel adds to the component (strudel-init). It would be good to have that value declared in Strudel to be able to import it from the dependent modules.

**Describe the solution you'd like**
Export initialised component's class name.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mateuszluczak** [comment]
Hey @pawel-staniszewski,

This is currently available from components, if you do in your component:

```
this.getInstance().config.initializedClassName
```

Probably API should be a little bit nicer
