### ISSUE TITLE
Elements find function sometimes fails due to invalid ID in selector

### ISSUE THREAD

**Issue by jakublamprecht** [strudeljs/strudel#94]
**Describe the bug**
If selector for find starts with `>`, then ID for current element is generated. There's an issue where this random ID will start with a number which will cause the querySelectorAll to fail.

**To Reproduce**
1. Use @El or .find with `>` at the beginning of selector
2. Refresh the component (possibly a few times, since it's a random behaviour)

**Expected behavior**
Find doesn't fail and finds element with specified selector

**Comment by mateuszluczak** [comment]
@zofoklecja 

![image](https://frankdenneman.nl/wp-content/uploads/2018/04/9yXav.gif)

LOLJK

Funny though it slipped through unit tests that sometimes it doesn't work :)

**Comment by zofoklecja** [comment]
I should've written more test cases I guess 😛
